suites:
  main:
    namespace: Appocular\Keeper
    psr4_prefix: Appocular\Keeper
    src_path: app

extensions:
  LeanPHP\PhpSpec\CodeCoverage\CodeCoverageExtension:
    format:
      - php
    output:
      php: coverage/spec.cov
    whitelist:
      - app
formatter.name: pretty
