suites:
  main:
    namespace: Ogle\Keeper
    psr4_prefix: Ogle\Keeper
    src_path: app

extensions:
  PhpSpec\Laravel\Extension\LaravelExtension:
    testing_environment: "testing"
  LeanPHP\PhpSpec\CodeCoverage\CodeCoverageExtension:
    format:
      - clover
    output:
      clover: clover.xml
    whitelist:
      - app
formatter.name: pretty
