language: php

php:
  - '7.2'

install: composer install --prefer-source

before_install:
  - npm install dredd@5.2.0 --no-optional --global

script:
  - ./vendor/bin/phpspec run
  - make coverage-clover
  - bash <(curl -s https://codecov.io/bash) -c -F spec -n Spec
  - env REPORT_COVERAGE=true dredd
  - make coverage-clover
  - bash <(curl -s https://codecov.io/bash) -c -F api -n API
