language: php

php:
  - '7.2'

install: composer install --prefer-source

before_install:
  - npm install dredd@11.2.11 --no-optional --global

script:
  - make test-spec
  - make coverage-clover
  - bash <(curl -s https://codecov.io/bash) -c -F spec -n Spec
  - make test-unit
  - make coverage-clover
  - bash <(curl -s https://codecov.io/bash) -c -F unit
  - make test-api
  - make coverage-clover
  - bash <(curl -s https://codecov.io/bash) -c -F api -n API
