FORMAT: 1A

# Keeper

Keeper is a simple image store for Appocular. It indexes images by
their image data, so each image is only stored once.

It is idempotent, so storing the same image will simply return the
same Keeper URL.

## Images resource [/image]

### Add image [POST]

Add an image to the image store. This is idempotent, if the image is
already stored, the return URL is the same.

+ Request (image/png)

        <PNG image data>

+ Response 201

    + Headers

            Location: http://localhost:8080/image/240e7948f07080dfe9671daa320bbb6e4e18ced5ff2d95e89bf59ce6784963bd

+ Request Bad request (image/png)

        <bad PNG image data>

+ Response 400 (text/plain; charset=UTF-8)

        Invalid image data.

+ Response 500 (text/plain; charset=UTF-8)

        Internal server error.

## Image [/image/{id}]

This is the resource for images. Storing images returns full URLs, so
there's no need to construct requests to this resource. It's
documented for completeness sake though.

+ Parameters
  + id: `240e7948f07080dfe9671daa320bbb6e4e18ced5ff2d95e89bf59ce6784963bd` (string) - Keeper ID of the image

### Get image [GET]

Returns an URL to the image with the given hash.

+ Request (text/plain)

+ Response 200 (image/png)

        <PNG image data>

+ Request Not found (text/plain)

    + Parameters

        + id: `invalid`

+ Response 404 (text/plain; charset=UTF-8)

        Not found.
