FORMAT: 1A

# Keeper

Keeper is a simple image store for Appocular. It indexes images by
their image data, so each image is only stored once.

It is idempotent, so storing the same image will simply return the
same ID.

## Images resource [/api/v1/image]

### Add image [POST]

Add an image to the image store. This is idempotent, if the image is
already stored, the SHA is simply returned.

+ Request (image/png)

        <PNG image data>

+ Response 200 (application/json)

        {
            "sha": "3a14fed556280d45d1542e9723d3cc62326c3777"
        }

+ Response 400 (application/json)

        {
            "error": "Invalid image data."
        }

## Image [/api/v1/image/{sha}]

+ Parameters
  + sha: `3a14fed556280d45d1542e9723d3cc62326c3777` (string) - SHA of the image

### Get image [GET]

Returns an URL to the image with the given SHA.

+ Request (application/json)

+ Response 302

    + Headers

            Location: http://server/storage/3a14fed556280d45d1542e9723d3cc62326c3777.png

+ Response 404 (application/json)

        {
            "error": "Not found"
        }
